<?php

namespace App\controllers;


class adminController extends Controller
{
    public function __construct()
    {
    }

    public function indexAction()
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function bd()
    {
        return parent::bd(); // TODO: Change the autogenerated stub
    }

}